### ISSUE TITLE
Scalar type hints are missing backslashes in docblocks

### ISSUE THREAD

**Issue by dcelasun** [chobie/protoc-gen-php#2]
Consider the following generated class:

```
<?php
namespace foo\bar;

// @@protoc_insertion_point(namespace:.foo.bar.GenericMessage)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: genericMessage.proto
 *
 * -*- magic methods -*-
 *
 * @method \foo\bar\MessageTypes getType()
 * @method void setType(\foo\bar\MessageTypes $value)
 * @method string getData()
 * @method void setData(string $value)
 */
```

The very last line has `setData(string $value)` but it should be `setData(\string $value)` because the class is namespaced. Without the `\` IDEs (like PhpStorm) complain with:

> Expected foo\bar\string, got string

This is a soft warning and doesn't affect execution, but it does mess up autocomplete.

Looks like an easy fix but I couldn't find the relevant point in the source code.

**Comment by chobie** [comment]
the block is here:
https://github.com/chobie/protoc-gen-php/blob/master/src/protocolbuffers/generator/php/MessageGenerator.php#L422

I'll look into this when I back to home.

**Comment by chobie** [comment]
I've checked with this proto file.

```
message Person
{
    message Phone
    {
        optional bytes number = 1;
    }
    optional Phone phone = 1;
    optional string name = 2;
    optional bytes bytes = 3;
    optional uint32 uint32 = 4;
    optional uint64 uint64 = 5;
    optional sint32 sint32 = 6;
    optional sint64 sint64 = 7;
}
```

show the generated files with phpstorm 7.1

![img](https://photos-4.dropbox.com/t/0/AAC-FEzsA_hTvWjLKYBMbSe6wQURdQ_9vsSlCL6kWl4TRQ/12/151611/png/2048x1536/3/1391612400/0/2/Screenshot%202014-02-05%2022.26.31.png/X14UQaTYGFGpdiAhiFZ8oF4AM490wKxUM3MgCUI7kmc)

Could you share proto file which can reproduce minimally this problem?

**Comment by dcelasun** [comment]
Here's a simple example:

```
package wom2.protobuf.messages;

import "messageTypes.proto";

message GenericMessage {
    optional MessageTypes type = 1;
    optional bytes data = 2;
}
```

I took a screenshot from my project:
![proto](https://f.cloud.github.com/assets/144373/2087588/5d40d2e4-8e6e-11e3-9199-ea2fc6d6a4b8.png)

Here's the first few lines of the generated class:

```
<?php
namespace wom2\protobuf\messages;

// @@protoc_insertion_point(namespace:.wom2.protobuf.messages.GenericMessage)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: genericMessage.proto
 *
 * -*- magic methods -*-
 *
 * @method \wom2\protobuf\messages\MessageTypes getType()
 * @method void setType(\wom2\protobuf\messages\MessageTypes $value)
 * @method string getData()
 * @method void setData(string $value)
```

Last 2 lines should be:

```
 * @method \string getData()
 * @method void setData(\string $value)
```

if there is a namespace covering the class.

**Comment by chobie** [comment]
ah, got it. I've just misunderstood. I meant that method expects string parameter but phpdoc intepret `string` as class.

let me remove that needless scalar type hints.

**Comment by dcelasun** [comment]
No no no! Don't remove them, just add a namespace prefix. Like `\string` instead of `string` :) PhpStorm supports scalar type hints just fine, and it would be a shame to lose them.

**Comment by chobie** [comment]
ok, wait a seconds

**Comment by dcelasun** [comment]
Excellent, thanks!
