### ISSUE TITLE
Append methods for repeated fields have wrong type hints

### ISSUE THREAD

**Issue by dcelasun** [chobie/protoc-gen-php#3]
Let me explain this one with a proto file and a screenshot of the generated class.

```
package wom2.protobuf.messages;

import "resultCodes.proto";
import "webUser.proto";

message LoginAsResponseMessage
{
    required ResultCodes resultCode = 1;
    repeated WebUser users = 2;
}
```

This proto file, turns into this generated class:

![protobug](https://f.cloud.github.com/assets/144373/2137407/8314c7c6-9325-11e3-9309-456fa379e074.png)

The type hint at line 15 should be:

```
* @method void appendUsers(\wom2\protobuf\messages\WebUser $value)
```

instead of

```
* @method void appendUsers(array $value)
```

**Comment by chobie** [comment]
thanks spotting it. let me look into it

**Comment by chobie** [comment]
Ah, sorry. I've just missed to pass repeated flag to that function.

**Comment by dcelasun** [comment]
Great, thanks!

**Comment by dcelasun** [comment]
Also, can you tag your commits? That way people can use version numbers in their `composer.json` and Packagist gets updated much faster.

**Comment by chobie** [comment]
@dcelasun okay, I've tagged it as 0.1.0.

**Comment by dcelasun** [comment]
Thanks!
